apiversion: v2
name: onecx-data-orchestrator
version: 0.0.0
appversion: 0.0.0
dependencies:
- name: helm-product
  version: ^0
  repository: oci://ghcr.io/onecx/charts
  alias: product
- name: onecx-data-orchestrator-operator
  version: "*-0"
  repository: oci://ghcr.io/onecx/charts
  condition: "deployment.operator"
  alias: "operator"
- name: onecx-data-orchestrator-bff
  version: "*-0"
  repository: oci://ghcr.io/onecx/charts
  condition: "deployment.bff"
  alias: "bff"
- name: onecx-data-orchestrator-ui
  version: "*-0"
  repository: oci://ghcr.io/onecx/charts
  condition: "deployment.ui"
  alias: "ui"